server:
   port: 8771

spring:
   application:
      name: gateway-service
   cloud:
     gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
            allowedHeaders:
              - content-type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowCredentials: true
            
      routes:
         - id: cancellazione-hr-service
           uri: 'http://localhost:8206'
           predicates:
            - Path=/rest/api/hr/cancellazione/**
         - id: gestione-hr-service
           uri: 'http://localhost:8211'
           predicates:
            - Path=/rest/api/hr/utenti/custom
         - id: inserimento-tecnologia-service
           uri:  'http://localhost:8210'
           predicates:
            - Path=/rest/api/tecnologie/lettura-categorie
         - id: inserimento-tecnologia-service
           uri:  'http://localhost:8210'
           predicates:
            - Path=/rest/api/tecnologie/**
         - id: inserimento-categoria-service
           uri:  'http://localhost:8209'
           predicates:
            - Path=/rest/api/categorie/**
         - id: login-dipendente-service
           uri:  'http://localhost:8202'
           predicates:
            - Path=/rest/api/dipendenti/login-dipendente
         - id: login-dipendente-service
           uri: 'http://localhost:8202'
           predicates:
             - Path=/rest/api/dipendenti/reset-token
         - id: login-hr-service
           uri:  'http://localhost:8207'
           predicates:
            - Path=/rest/api/hr/login-hr
         - id: modifica-dipendente-service
           uri:  'http://localhost:8201'
           predicates:
            - Path=/rest/api/dipendenti/modifica-dipendente
         - id: modifica-dipendente-service
           uri: 'http://localhost:8201'
           predicates:
             - Path=/rest/api/dipendenti/ottieni-dipendente
         - id: modifica-dipendente-service
           uri: 'http://localhost:8201'
           predicates:
             - Path=/rest/api/dipendenti/ciao
         - id: aggiornamento-hr-service
           uri:  'http://localhost:8205'
           predicates:
            - Path=/rest/api/hr/modifica/**
         - id: registrazione-dipendente-service
           uri:  'http://localhost:8200'
           predicates:
            - Path=/rest/api/registrazione-dipendenti/**
         - id: registrazione-hr-service
           uri:  'http://localhost:8204'
           predicates:
            - Path=/rest/api/registrazione-hr/**
         - id: ricerca-dipendenti-service
           uri:  'http://localhost:8208'
           predicates:
            - Path=/rest/api/dipendenti-per-tecnologie/**
         - id: competenza-service
           uri:  'http://localhost:8203'
           predicates:
            - Path=/rest/api/competenze/associa-dipendente-tecnologie
         - id: inserimento-tecnologia-service
           uri: 'http://localhost:8210'
           predicates:
             - Path=/rest/api/tecnologie/tecnologie
         - id: competenza-service
           uri: 'http://localhost:8203'
           predicates:
             - Path=/rest/api/competenze/tecnologie
         - id: competenza-service
           uri: 'http://localhost:8203'
           predicates:
             - Path=/rest/api/competenze/tecnologie-del-dipendente
         - id: gestione-hr-service
           uri: 'http://localhost:8211'
           predicates:
             - Path=/rest/api/hr/trovaHr
         - id: gestione-hr-service
           uri: 'http://localhost:8211'
           predicates:
             - Path=/rest/api/hr/dipendenti-competenze/tecnologie
         - id: recupero-password-service
           uri: 'http://localhost:8212'
           predicates:
             - Path=/rest/api/recupero-password
         - id: recupero-password-service
           uri: 'http://localhost:8212'
           predicates:
             - Path=/rest/api/verifica-token
         - id: cancellazione-categoria-service
           uri: 'http://localhost:8213'
           predicates:
             - Path=/rest/api/cancellazione-categoria/**
         - id: cancellazione-tecnologia-service
           uri: 'http://localhost:8214'
           predicates:
             - Path=/rest/api/cancellazione-tecnologia
         - id: certificazioni-service
           uri: 'http://localhost:8215'
           predicates:
             - Path=/rest/api/certificazioni/nuova-certificazione
         - id: certificazioni-service
           uri: 'http://localhost:8215'
           predicates:
             - Path=/rest/api/certificazioni/cancellazione-certificazione/**
         - id: certificazioni-service
           uri: 'http://localhost:8215'
           predicates:
             - Path=/rest/api/certificazioni/lista-certificazioni